"""Type stub for AbstractUser."""

from typing import Any
from uuid import UUID

from sqlalchemy.orm import Mapped

class AbstractUser:
    """Abstract User model with email/password auth, roles, and domain support."""

    __abstract__: bool
    __tablename__: str
    __table_args__: dict[str, Any]

    id: UUID
    email: Mapped[str]
    password: Mapped[bytes | None]
    is_enabled: Mapped[bool]

    roles: Any
    settings: Any
    tokens: Any

    def __init__(self, **kwargs: Any) -> None: ...
    def get_current_user(self) -> Any | None: ...
    def set_password(self, password: str) -> None: ...
    def is_password_correct(self, password: str) -> bool: ...
    def update(self, commit: bool = True, **kwargs: Any) -> None: ...
    def save(self, commit: bool = True) -> None: ...
    def delete(self, commit: bool = True) -> None: ...
    @property
    def is_admin(self) -> bool: ...
    @property
    def is_superadmin(self) -> bool: ...
    def has_role(self, role: str, domain_name: str | None = None) -> bool: ...
    def list_roles(self) -> list[str]: ...
    def _can_read(self, user: Any | None) -> bool: ...
    def _can_write(self, user: Any | None) -> bool: ...
    def _can_create(self, user: Any | None) -> bool: ...
    @property
    def num_tokens(self) -> int: ...
    @property
    def domain_ids(self) -> set[UUID | str]: ...
    def has_domain_access(self, domain_id: UUID | None) -> bool: ...
